{
 "title": "Altibase Monitoring",
 "tags": [
  "altibase",
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values on telegraf from altibase with key = \"host\""
   },
   {
    "name": "dsn",
    "label": "dsn",
    "query": "show tag values on telegraf from altibase with key = \"dsn\""
   },
   {
    "name": "user",
    "label": "user",
    "query": "show tag values on telegraf from procstat with key = \"user\""
   },
   { "name": "inter", "label": "interval", "query": "10s,30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "/" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "/boot" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/boot" }
     ]
    },
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "/data" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage Details",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "cpu",
     "query": "SELECT 100 - last(\"usage_idle\") FROM \"autogen\".\"cpu\" WHERE \"host\" =~ /^$host$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "mem",
     "query": "SELECT last(\"free\"), last(\"used\") FROM \"autogen\".\"mem\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "/" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
     ]
    },
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "/boot" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/boot" }
     ]
    },
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "/data" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/data" }
     ]
    }
   ]
  },
  { "title": "Altibase OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Altibase Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "ALTIBASE_VERSION" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "user::tag", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "altibase_cpu_usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "user::tag", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "Memstat",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "MEMSTAT_MAX_TOTAL" ], "type": "field" },
       { "params": [ "max_total" ], "type": "alias" }
      ],
      [
       { "params": [ "MEMSTAT_ALLOC" ], "type": "field" },
       { "params": [ "alloc" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory GC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "query": "SELECT last(\"MEM_DELTHR\"), last(\"MEM_LOGICAL_AGER\") FROM \"autogen\".\"altibase\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MEM_DELTHR" ], "type": "field" },
       { "params": [ "mem_delthr" ], "type": "alias" }
      ],
      [
       { "params": [ "MEM_LOGICAL_AGER" ], "type": "field" },
       { "params": [ "mem_logical_ager" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "WORKING_TIME" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase PID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "user::tag", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase Memory Usage (RSS)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "user::tag", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "altibase_memory_rss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "user::tag", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "Rep Sender Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "REP_SENDER_COUNT" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Rep Gap",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_rep_gap",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       { "params": [ "_" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Logfile Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "LOGFILE_GAP" ], "type": "field" },
       { "params": [ "logfile_gap" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads of Altibase",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "user::tag", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "Rep Receiver Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "REP_RECEIVER_COUNT" ], "type": "field" },
       { "params": [ "rep_receiver_count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "LF Prepare Wait Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "LF_PREPARE_WAIT_COUNT" ], "type": "field" },
       { "params": [ "lf_prepare_wait_count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Archive Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "ARCHIVE_MODE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "ServiceThread Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_srv_thr",
     "select": [
      [
       { "params": [ "TOTAL_COUNT" ], "type": "field" },
       { "params": [ "service_thread_count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "SESSION_COUNT" ], "type": "field" },
       { "params": [ "Sesson Count" ], "type": "alias" }
      ],
      [
       { "params": [ "STATEMENT_COUNT" ], "type": "field" },
       { "params": [ "Statement Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_srv_thr",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       { "params": [ "Executing Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "LONG_RUN_QUERY_COUNT" ], "type": "field" },
       { "params": [ "Long-run Query Count" ], "type": "alias" }
      ],
      [
       { "params": [ "UTRANS_QUERY_COUNT" ], "type": "field" },
       { "params": [ "Utrans Query Count" ], "type": "alias" }
      ],
      [
       { "params": [ "FULLSCAN_QUERY_COUNT" ], "type": "field" },
       { "params": [ "Full-scan Query Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Lock Query",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase",
     "query": "SELECT last(\"LOCK_HOLD_COUNT\") AS \"lock_hold_count\", last(\"LOCK_WAIT_COUNT\") AS \"lock_wait_count\" FROM \"autogen\".\"altibase\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "LOCK_HOLD_COUNT" ], "type": "field" },
       { "params": [ "Num of Holding Locks" ], "type": "alias" }
      ],
      [
       { "params": [ "LOCK_WAIT_COUNT" ], "type": "field" },
       { "params": [ "Num of Waiting Locks" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "Session & Statement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Session Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "SESSION_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session_count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Statement Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "STATEMENT_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "statement_count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "ServiceThread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "ServiceThread State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_thr",
     "query": "SELECT last(*) FROM \"autogen\".\"altibase_srv_thr\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "EXECUTE" ], "type": "alias" }
      ],
      [
       { "params": [ "TOTAL_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TOTAL_COUNT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "ServiceThread Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_thr",
     "select": [
      [
       { "params": [ "IPC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPC" ], "type": "alias" }
      ],
      [
       { "params": [ "SOCKET(MULTIPLEXING)" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "MULTIPLEXING" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "ServiceThread Run Mode",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_thr",
     "select": [
      [
       { "params": [ "DEDICATED" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DEDICATED" ], "type": "alias" }
      ],
      [
       { "params": [ "SHARED" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SHARED" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "Altibase Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memstat Usage Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "MEMSTAT_ALLOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memstat_alloc" ], "type": "alias" }
      ],
      [
       { "params": [ "MEMSTAT_MAX_TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memstat_max_total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Tablespace Usage (Alloc)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_tbs_total",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Memstat Usage Details - Max Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_memstat_max",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Tablespace Usage (%) - Used/Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_tbs_usage",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Memstat Usage Details - Alloc",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_memstat_alloc",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Memory Table Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_mem_tbl_usage",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Disk Table Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_disk_tbl_usage",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "BufferPool Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Buffpool_stat's Hit Ratio(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "hit_ratio" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffpool_stat's Victim_Fails",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "VICTIM_FAILS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "victim_fails" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "Memory GC & Logfile Gap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Memory GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "MEM_DELTHR" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "mem_delthr" ], "type": "alias" }
      ],
      [
       { "params": [ "MEM_LOGICAL_AGER" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "mem_logical_ager" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Logfile Gap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase",
     "select": [
      [
       { "params": [ "LOGFILE_GAP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "logfile_gap" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions that the GC is waiting for",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "30",
     "measurement": "altibase_tx_of_memory_view_scn",
     "select": [
      [
       { "params": [ "SESSION_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SESSION_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "TX_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "EXECUTE_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "EXECUTE_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "TOTAL_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TOTAL_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "QUERY" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "QUERY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "Sysstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Sysstat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_sysstat",
     "select": [
      [
       { "params": [ "execute success count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "execute_success_count" ], "type": "alias" }
      ],
      [
       { "params": [ "execute failure count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "execute_failure_count" ], "type": "alias" }
      ],
      [
       { "params": [ "prepare success count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "prepare_success_count" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "memory table cursor full scan count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "memory_table_full_scan_count" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "disk table cursor full scan count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "disk_table_full_scan_count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Altibase File IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true
  },
  {
   "title": "Filestat's Phyrds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_file_io_reads",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "_" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Filestat's Phywrts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_file_io_writes",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "_" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Filestat's IO Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_file_io_wait",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "System & Session Event", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "System Event (time_waited)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_system_event",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Session Event (time_waited)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "1",
     "measurement": "altibase_session_event",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "Query Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Top Long-run Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "30",
     "measurement": "altibase_long_run_query",
     "select": [
      [
       { "params": [ "SESSION_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SESSION_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "STMT_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "STMT_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "TX_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "LAST_START_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "LAST_START_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "EXECUTE_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "EXECUTE_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "TOTAL_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TOTAL_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "QUERY" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "QUERY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Utrans Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "30",
     "measurement": "altibase_utrans_query",
     "select": [
      [
       { "params": [ "SESSION_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SESSION_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "CLIENT_APP_INFO" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CLIENT_APP_INFO" ], "type": "alias" }
      ],
      [
       { "params": [ "CLIENT_IP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CLIENT_IP" ], "type": "alias" }
      ],
      [
       { "params": [ "LAST_START_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "LAST_START_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "EXECUTE_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "EXECUTE_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "UTRANS_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UTRANS_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "TOTAL_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TOTAL_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "QUERY" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "QUERY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Full-scan Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "30",
     "measurement": "altibase_fullscan_query",
     "select": [
      [
       { "params": [ "SESSION_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SESSION_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "CLIENT_APP_INFO" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CLIENT_APP_INFO" ], "type": "alias" }
      ],
      [
       { "params": [ "CLIENT_IP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CLIENT_IP" ], "type": "alias" }
      ],
      [
       { "params": [ "LAST_START_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "LAST_START_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "EXECUTE_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "EXECUTE_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "FETCH_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FETCH_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "TOTAL_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TOTAL_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "QUERY" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "QUERY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "Lock Wait Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Top Lock Hold Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "30",
     "measurement": "altibase_lock_hold_info",
     "select": [
      [
       { "params": [ "TABLE_NAME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TABLE_NAME" ], "type": "alias" }
      ],
      [
       { "params": [ "SESSION_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SESSION_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "TX_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "TOTAL_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TOTAL_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "QUERY" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "QUERY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Lock Wait Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "30",
     "measurement": "altibase_lock_wait_info",
     "select": [
      [
       { "params": [ "TABLE_NAME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TABLE_NAME" ], "type": "alias" }
      ],
      [
       { "params": [ "SESSION_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SESSION_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "TX_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "WAIT_FOR_TX_ID" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "WAIT_FOR_TX_ID" ], "type": "alias" }
      ],
      [
       { "params": [ "TOTAL_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TOTAL_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "QUERY" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "QUERY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dsn::tag", "operator": "=~", "value": "/^$dsn$/" }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } }
 ]
}